#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
TFVARS_FILE="${ROOT_DIR}/infra/terraform/terraform.tfvars"

WIREGUARD_SUBNET="${WIREGUARD_SUBNET:-10.0.0.0/24}"
WIREGUARD_SERVER_IP="${WIREGUARD_SERVER_IP:-10.0.0.1}"
DNS_ZONE="${DNS_ZONE:-intranet.local}"
SERVICE_HOSTNAME="${SERVICE_HOSTNAME:-service1.intranet.local}"
SERVICE_CONTAINER_IMAGE="${SERVICE_CONTAINER_IMAGE:-netlab/service1:latest}"
COREDNS_IMAGE="${COREDNS_IMAGE:-coredns/coredns:1.12.0}"

log() { echo "[local-config] $*"; }
err() { echo "[local-config][error] $*" >&2; }

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

load_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -a
    source "${ENV_FILE}"
    set +a
  fi
}

ensure_sudo_password() {
  if [[ -z "${SUDO_PASSWORD:-}" ]]; then
    read -rsp "Enter sudo password for local host: " SUDO_PASSWORD
    echo

    if [[ -f "${ENV_FILE}" ]]; then
      if grep -q '^SUDO_PASSWORD=' "${ENV_FILE}"; then
        sed -i "s|^SUDO_PASSWORD=.*$|SUDO_PASSWORD=${SUDO_PASSWORD}|" "${ENV_FILE}"
      else
        printf '\nSUDO_PASSWORD=%s\n' "${SUDO_PASSWORD}" >> "${ENV_FILE}"
      fi
    else
      printf 'SUDO_PASSWORD=%s\n' "${SUDO_PASSWORD}" > "${ENV_FILE}"
    fi
    chmod 600 "${ENV_FILE}"
  fi
}

sudo_run() {
  echo "${SUDO_PASSWORD}" | sudo -S "$@"
}

ensure_ssh_server() {
  if ss -ltn '( sport = :22 )' | grep -q ':22'; then
    log "SSH server already listening on port 22"
    return
  fi

  log "No SSH server detected. Installing/starting OpenSSH server"

  if command_exists apt-get; then
    sudo_run apt-get update -y >/dev/null
    sudo_run apt-get install -y openssh-server >/dev/null
    sudo_run systemctl enable --now ssh
  elif command_exists dnf; then
    sudo_run dnf install -y openssh-server >/dev/null
    sudo_run systemctl enable --now sshd
  elif command_exists pacman; then
    sudo_run pacman -Sy --noconfirm openssh >/dev/null
    sudo_run systemctl enable --now sshd
  else
    err "Unsupported package manager; cannot auto-install SSH server"
    exit 1
  fi

  if ! ss -ltn '( sport = :22 )' | grep -q ':22'; then
    err "SSH server failed to start on port 22"
    exit 1
  fi

  log "SSH server started on port 22"
}

detect_server_public_ip() {
  if [[ -n "${SERVER_PUBLIC_IP:-}" ]]; then
    echo "${SERVER_PUBLIC_IP}"
    return
  fi

  local ip_candidate
  ip_candidate="$(hostname -I 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i !~ /^127\./) {print $i; exit}}')"

  if [[ -z "${ip_candidate}" ]]; then
    ip_candidate="$(ip route get 1.1.1.1 2>/dev/null | awk '/src/ {for (i=1; i<=NF; i++) if ($i == "src") {print $(i+1); exit}}')"
  fi

  if [[ -z "${ip_candidate}" ]]; then
    err "Could not detect server_public_ip automatically"
    exit 1
  fi

  echo "${ip_candidate}"
}

detect_ssh_user() {
  if [[ -n "${SERVER_SSH_USER:-}" ]]; then
    echo "${SERVER_SSH_USER}"
  else
    echo "${USER}"
  fi
}

detect_ssh_key_file() {
  if [[ -n "${SERVER_SSH_PRIVATE_KEY_FILE:-}" ]]; then
    echo "${SERVER_SSH_PRIVATE_KEY_FILE}"
    return
  fi

  local key
  for key in "${HOME}/.ssh/id_ed25519" "${HOME}/.ssh/id_rsa"; do
    if [[ -f "${key}" ]]; then
      echo "${key}"
      return
    fi
  done

  log "No SSH private key found. Generating ${HOME}/.ssh/id_ed25519"
  mkdir -p "${HOME}/.ssh"
  chmod 700 "${HOME}/.ssh"
  ssh-keygen -t ed25519 -N "" -f "${HOME}/.ssh/id_ed25519" -q
  echo "${HOME}/.ssh/id_ed25519"
}

write_tfvars() {
  local server_ip ssh_user ssh_port ssh_key
  server_ip="$(detect_server_public_ip)"
  ssh_user="$(detect_ssh_user)"
  ssh_port="${SERVER_SSH_PORT:-22}"
  ssh_key="$(detect_ssh_key_file)"

  cat > "${TFVARS_FILE}" <<EOF
# Auto-generated by infra/scripts/local-config.sh
server_public_ip            = "${server_ip}"
server_ssh_user             = "${ssh_user}"
server_ssh_port             = ${ssh_port}
server_ssh_private_key_file = "${ssh_key}"

# Optional managed clients (Ansible will configure them automatically).
# Keep empty when connecting additional computers via connect-client.sh.
client_hosts = []

# VPN network defaults
wireguard_subnet    = "${WIREGUARD_SUBNET}"
wireguard_server_ip = "${WIREGUARD_SERVER_IP}"

# Internal DNS + service defaults
dns_zone                = "${DNS_ZONE}"
service_hostname        = "${SERVICE_HOSTNAME}"
service_container_image = "${SERVICE_CONTAINER_IMAGE}"
coredns_image           = "${COREDNS_IMAGE}"
EOF

  log "Wrote ${TFVARS_FILE}"
}

validate_config() {
  if command_exists terraform; then
    terraform -chdir="${ROOT_DIR}/infra/terraform" fmt -write=true terraform.tfvars >/dev/null || true
    terraform -chdir="${ROOT_DIR}/infra/terraform" validate >/dev/null || true
  fi

  log "Configuration generated and ready for provisioning"
  log "Next steps: make infra && make ssh-check && make config && make deploy && make test"
}

main() {
  load_env
  ensure_sudo_password
  ensure_ssh_server
  write_tfvars
  validate_config
}

main "$@"
