locals {
  root_dir          = abspath("${path.module}/../..")
  ansible_dir       = "${local.root_dir}/infra/ansible"
  generated_dir     = "${local.root_dir}/infra/ansible/generated"
  inventory_path    = "${local.generated_dir}/inventory.ini"
  tfvars_example    = "${path.module}/terraform.tfvars.example"
  generated_message = "Generated by Terraform. Do not edit manually."

  clients_inventory = [
    for client in var.client_hosts :
    join(" ", compact([
      client.name,
      "ansible_host=${client.ansible_ip}",
      "ansible_user=${try(client.ssh_user, var.server_ssh_user)}",
      "ansible_port=${try(client.ssh_port, 22)}",
      length(trimspace(try(client.ssh_private_key_file, ""))) > 0 ? "ansible_ssh_private_key_file=${trimspace(try(client.ssh_private_key_file, ""))}" : ""
    ]))
  ]

  server_inventory_line = join(" ", compact([
    "vpn-server",
    "ansible_host=${var.server_public_ip}",
    "ansible_user=${var.server_ssh_user}",
    "ansible_port=${var.server_ssh_port}",
    length(trimspace(var.server_ssh_private_key_file)) > 0 ? "ansible_ssh_private_key_file=${trimspace(var.server_ssh_private_key_file)}" : ""
  ]))

  inventory_content = join("\n", compact([
    "; ${local.generated_message}",
    "[wireguard_server]",
    local.server_inventory_line,
    "",
    "[wireguard_clients]",
    length(local.clients_inventory) > 0 ? join("\n", local.clients_inventory) : "",
    "",
    "[all:vars]",
    "wireguard_subnet=${var.wireguard_subnet}",
    "wireguard_server_ip=${var.wireguard_server_ip}",
    "dns_zone=${var.dns_zone}",
    "service_hostname=${var.service_hostname}",
    "service_container_image=${var.service_container_image}",
    "coredns_image=${var.coredns_image}"
  ]))

  tfvars_example_content = <<-EOT
    # Copy this file to terraform.tfvars and adjust values.
    server_public_ip = "203.0.113.10"
    server_ssh_user  = "ubuntu"
    server_ssh_port  = 22
    server_ssh_private_key_file = "/home/your-user/.ssh/id_ed25519"

    client_hosts = [
      {
        name       = "client-1"
        ansible_ip = "203.0.113.20"
        ssh_user   = "ubuntu"
        ssh_port   = 22
        ssh_private_key_file = "/home/your-user/.ssh/id_ed25519"
      }
    ]

    wireguard_subnet    = "10.0.0.0/24"
    wireguard_server_ip = "10.0.0.1"
    dns_zone            = "intranet.local"
    service_hostname    = "service1.intranet.local"
    service_container_image = "netlab/service1:latest"
    coredns_image       = "coredns/coredns:1.12.0"
  EOT
}

resource "null_resource" "create_generated_dir" {
  provisioner "local-exec" {
    command = "mkdir -p ${local.generated_dir}"
  }
}

resource "local_file" "inventory" {
  depends_on      = [null_resource.create_generated_dir]
  filename        = local.inventory_path
  content         = local.inventory_content
  file_permission = "0644"
}

resource "local_file" "tfvars_example" {
  filename        = local.tfvars_example
  content         = trimspace(local.tfvars_example_content)
  file_permission = "0644"
}
